Repository Project-MONAI/monai-deploy-app-sdk, pull requests merged in 2021-11, with the labels that each got.

#168 Build package with local UID/GID and fast-retrieve app/package information
  monai/deploy/packager/util.py
  monai/deploy/runner/runner.py
Labels: bug

#167 Force to remap to CPU for TorchScript model if GPUdoesn't exist
  examples/apps/mednist_classifier_monaideploy/mednist_classifier_monaideploy.py
  monai/deploy/core/models/torch_model.py
  monai/deploy/operators/monai_seg_inference_operator.py
  notebooks/tutorials/02_mednist_app-prebuilt.ipynb
  notebooks/tutorials/02_mednist_app.ipynb
Labels: bug

#205 Release v0.2.0
  .bumpversion.cfg
  docs/source/developing_with_sdk/deploying_to_the_remote_server.md
  docs/source/getting_started/tutorials/04_mis_tutorial.md
  docs/source/getting_started/tutorials/05_full_tutorial.md
  docs/source/getting_started/tutorials/index.md
  docs/source/release_notes/index.md
Labels: architectural story

#209 Fix minor typo in chapter 4 notebook
  notebooks/tutorials/04_mis_tutorial.ipynb
Labels: documentation
