Repository Project-MONAI/monai-deploy-app-sdk, pull requests merged in 2021-09, with the labels that each got.

#136 Update Architecture and Core Concepts docs
  CONTRIBUTING.md
  README.md
  docs/_static/custom.css
  docs/source/conf.py
  docs/source/developing_with_sdk/core_concepts.md
  docs/source/developing_with_sdk/designing_workflow.md
  docs/source/developing_with_sdk/index.md
  docs/source/introduction/architecture.md
  docs/source/introduction/contributing.md
  docs/source/introduction/index.md
  docs/source/introduction/overview.md
  docs/source/modules/datastores.md
  docs/source/modules/executors.md
  docs/source/modules/graphs.md
  docs/source/modules/index.md
  examples/apps/dicom_series_to_image_app/app.py
  examples/apps/lung_seg_cv_app/lun_seg_test.py
  monai/deploy/cli/exec_command.py
  monai/deploy/cli/main.py
  monai/deploy/core/__init__.py
  monai/deploy/core/app_context.py
  monai/deploy/core/datastores/__init__.py
  monai/deploy/core/datastores/datastore.py
  monai/deploy/core/datastores/factory.py
  monai/deploy/core/domain/dicom_study.py
  monai/deploy/core/executors/__init__.py
  monai/deploy/core/executors/executor.py
  monai/deploy/core/executors/factory.py
  monai/deploy/core/executors/multi_process_executor.py
  monai/deploy/core/executors/multi_threaded_executor.py
  monai/deploy/core/graphs/__init__.py
  monai/deploy/core/graphs/factory.py
  monai/deploy/core/io_type.py
  monai/deploy/core/models/__init__.py
  monai/deploy/exceptions.py
  monai/deploy/packager/__init__.py
  monai/deploy/runner/utils.py
  pyproject.toml
  run
  setup.cfg
  setup.py
  tests/conftest.py
  tests/system/packager/test_packager.py
Labels: documentation, architectural story

#138 Fix flake8 error regarding exception chaining
  monai/deploy/core/io_context.py
  monai/deploy/core/resource.py
  tests/unit/test_runner.py
  tests/unit/test_runner_utils.py
Labels: architectural story

#141 Update docs for MONAI Application Runner's input
  README.md
  docs/source/developing_with_sdk/core_concepts.md
  docs/source/developing_with_sdk/executing_packaged_app_locally.md
  docs/source/developing_with_sdk/packaging_app.md
  examples/apps/mednist_classifier_monaideploy/mednist_classifier_monaideploy.py
  examples/apps/simple_imaging_app/sobel_operator.py
  monai/deploy/cli/exec_command.py
  monai/deploy/core/domain/image.py
  monai/deploy/packager/package_command.py
  monai/deploy/packager/util.py
  monai/deploy/runner/README.md
  monai/deploy/runner/run_command.py
  notebooks/tutorials/01_simple_app.ipynb
  notebooks/tutorials/02_mednist_app.ipynb
  notebooks/tutorials/03_segmentation_app.ipynb
Labels: documentation, architectural story

#144 Fix pydicom dependency
  monai/deploy/core/domain/dicom_sop_instance.py
Labels: bug, architectural story

#147 Derived app class needs to support args and kwargs in the run function.
  examples/apps/ai_spleen_seg_app/app.py
  examples/apps/ai_unetr_seg_app/app.py
Labels: bug

#149 Update user guide for SDK - part 2 (0.1.0rc2 → 0.1.0rc3)
  .bumpversion.cfg
  README.md
  docs/source/_templates/sidebar-quicklinks.html
  docs/source/conf.py
  docs/source/developing_with_sdk/core_concepts.md
  docs/source/developing_with_sdk/creating_application_class.md
  docs/source/developing_with_sdk/creating_operator_classes.md
  docs/source/developing_with_sdk/designing_workflow.md
  docs/source/developing_with_sdk/executing_app_locally.ipynb
  docs/source/developing_with_sdk/executing_app_locally.md
  docs/source/developing_with_sdk/executing_packaged_app_locally.md
  docs/source/developing_with_sdk/index.md
  docs/source/getting_started/examples.md
  docs/source/getting_started/tutorials/01_simple_app.md
  docs/source/getting_started/tutorials/02_mednist_app.md
  docs/source/getting_started/tutorials/03_segmentation_app.md
  docs/source/introduction/architecture.md
  docs/source/introduction/overview.md
  docs/source/introduction/roadmap.md
  docs/source/release_notes/v0.1.0.md
  monai/deploy/core/env.py
  monai/deploy/core/operator.py
  monai/deploy/core/resource.py
  monai/deploy/utils/sizeutil.py
  notebooks/tutorials/01_simple_app.ipynb
  notebooks/tutorials/02_mednist_app-prebuilt.ipynb
  notebooks/tutorials/02_mednist_app.ipynb
  notebooks/tutorials/03_segmentation_app.ipynb
  run
Labels: documentation, architectural story

#150 Update tutorial videos and installation guide
  docs/source/getting_started/installing_app_sdk.md
  docs/source/getting_started/tutorials/01_simple_app.md
  docs/source/getting_started/tutorials/02_mednist_app.md
  docs/source/getting_started/tutorials/03_segmentation_app.md
  docs/source/modules/index.md
Labels: documentation, architectural story

#151 Release v0.1.0
  .bumpversion.cfg
  docs/source/introduction/roadmap.md
Labels: architectural story

#153 Use POSIX path for App Runner to handle Windows path
  .bumpversion.cfg
  docs/source/getting_started/installing_app_sdk.md
  monai/deploy/runner/runner.py
  monai/deploy/runner/utils.py
Labels: bug
