Repository Project-MONAI/monai-deploy-app-sdk, pull requests merged in 2022-08, with the labels that each got.

#327 Implement highdicom seg operator
  examples/apps/ai_livertumor_seg_app/app.py
  examples/apps/ai_spleen_seg_app/app.py
  examples/apps/ai_unetr_seg_app/app.py
  monai/deploy/operators/dicom_seg_writer_operator.py
  monai/deploy/operators/monai_bundle_inference_operator.py
  monai/deploy/operators/monai_seg_inference_operator.py
  requirements-dev.txt
  requirements-examples.txt
Labels: enhancement

#335 Fix the setting of init state in its own PR, instead of rolled into others
  monai/deploy/operators/monai_bundle_inference_operator.py
Labels: bug

#334 Add highdicom license to the Third Party Notices
  THIRD_PARTY_NOTICES/highdicom_MIT_LICENSE.txt
Labels: documentation
