Repository Project-MONAI/monai-deploy-app-sdk, pull requests merged in 2022-01, with the labels that each got.

#233 Fixed empty documentation on docs.monai
  docs/source/conf.py
  docs/source/index.md
  docs/source/modules/index.md
  monai/deploy/cli/exec_command.py
  monai/deploy/packager/package_command.py
  monai/deploy/runner/run_command.py
  run
Labels: documentation

#237 Fix IPython detection routine
  monai/deploy/core/application.py
  monai/deploy/utils/importutil.py
Labels: bug

#236 Handle exception case with missing DICOM Rescale Intercept and Slope attributes
  monai/deploy/operators/dicom_series_to_volume_operator.py
Labels: bug

#169 Make InMemImageReader work even when monai is not used/available
  monai/deploy/operators/monai_seg_inference_operator.py
Labels: bug

#241 Use Python 3.7 for JupyterLab
  docs/source/getting_started/tutorials/01_simple_app.md
  docs/source/getting_started/tutorials/02_mednist_app.md
  docs/source/getting_started/tutorials/03_segmentation_app.md
Labels: documentation

#247 Do not upgrade packages when packaging
  monai/deploy/packager/templates.py
Labels: bug

#248 Drop Python 3.6 support
  .github/workflows/pr.yml
  .readthedocs.yml
  docs/source/getting_started/installing_app_sdk.md
  docs/source/getting_started/tutorials/01_simple_app.md
  docs/srs.md
  pyproject.toml
  setup.cfg
Labels: enhancement

#250 Release v0.2.1
  .bumpversion.cfg
  README.md
  docs/requirements.txt
  docs/source/getting_started/tutorials/04_mis_tutorial.md
  docs/source/getting_started/tutorials/05_full_tutorial.md
  docs/source/release_notes/index.md
  docs/source/release_notes/v0.2.1.md
  examples/apps/ai_livertumor_seg_app/livertumor_seg_operator.py
  examples/apps/ai_spleen_seg_app/spleen_seg_operator.py
  examples/apps/ai_unetr_seg_app/unetr_seg_operator.py
  examples/apps/deply_app_on_aarch64_interim.md
  monai/deploy/operators/monai_seg_inference_operator.py
  monai/deploy/packager/templates.py
  notebooks/tutorials/03_segmentation_app.ipynb
  notebooks/tutorials/05_full_tutorial.ipynb
  requirements.txt
  setup.cfg
Labels: enhancement

#235 Add Clara Viz operator.
  monai/deploy/operators/__init__.py
  monai/deploy/operators/clara_viz_operator.py
  notebooks/tutorials/03_segmentation_viz_app.ipynb
Labels: enhancement
