Repository Project-MONAI/monai-deploy-app-sdk, pull requests merged in 2022-02, with the labels that each got.

#253 Update README.md
  README.md
Labels: documentation

#263 Add DICOMTextSRWriterOperator to the autosummary section for doc gene…
  monai/deploy/operators/__init__.py
  monai/deploy/operators/dicom_seg_writer_operator.py
  monai/deploy/operators/dicom_text_sr_writer_operator.py
  monai/deploy/utils/sizeutil.py
Labels: documentation

#265 Updated the png converter operator following changes to Image ndarray index order.
  monai/deploy/operators/png_converter_operator.py
Labels: bug

#271 fix: Address typos in bilinear mode usage in Spacingd operator
  examples/apps/ai_spleen_seg_app/spleen_seg_operator.py
  notebooks/tutorials/03_segmentation_app.ipynb
  notebooks/tutorials/03_segmentation_viz_app.ipynb
  notebooks/tutorials/05_full_tutorial.ipynb
Labels: bug, good first issue
