Repository Project-MONAI/monai-deploy-app-sdk, pull requests merged in 2022-04, with the labels that each got.

#284 Issue (#283) Fix shm issue
  monai/deploy/operators/monai_seg_inference_operator.py
Labels: enhancement

#285 Fix issue245 DICOM Seg has multiple slices of seg image on the same frame
  examples/apps/ai_livertumor_seg_app/app.py
  examples/apps/ai_unetr_seg_app/app.py
  monai/deploy/operators/dicom_seg_writer_operator.py
Labels: bug

#292 Release v0.3.0
  .bumpversion.cfg
  docs/source/release_notes/index.md
  docs/source/release_notes/v0.3.0.md
  notebooks/tutorials/03_segmentation_viz_app.ipynb
Labels: documentation

#293 Fix typo in v0.3.0 release note
  docs/source/release_notes/v0.3.0.md
Labels: documentation
